In [1]:
import numpy as np

In [ ]:
#신경망 구혀(w/o 라이브러리)

In [3]:
X=np.array([1,2,3,4])
np.ndim(X) #<-1차원 배열
#차원의 수
X.shape
#(2,3):2차원
#(2,3,4):3차원

(4,)

In [5]:
X=np.array([[1,2],[3,4],[5,6]])
np.ndim(X) #2차원 배열
X.shape  #(3,2) -> 3행2열
#0번째 차원에 원소 3개, 1번째 차원에 원소 2개
#행렬:2차원 배열로 표현

(3, 2)

In [6]:
X=np.array([[1,2],[3,4]])
Y=np.array([[5,6],[7,8]])
#행렬의 곱(내적) X*Y
np.dot(X,Y) # 행렬의 내적

array([[19, 22],
       [43, 50]])

In [9]:
X=np.array([1,2])
W=np.array([[1,3,5],[2,4,6]])
print(np.dot(X,W))

[ 5 11 17]


In [11]:
def sigmoid(x):
    return 1/ (1+np.exp(-x))

In [12]:
X=np.array([1.0,0.5])
W1=np.array([[0.1,0.3,0.5],
            [0.2,0.4,0.6],]) #(2,3)
B1=np.array([0.1,0.2,0.3])
H1=np.dot(X,W1)+B1
print(H1)
Z1=sigmoid(H1)
Z1

[0.3 0.7 1.1]


array([0.57444252, 0.66818777, 0.75026011])

In [ ]:
# [None,2] =[행,렬] -> 행이 None인 이유는 데이터가 2차원으로 몇개 들어올
# 지 모르기 때문에 계속 바뀌어야 해서(정해져있지 않아서)...tensorflow에서 많이씀

In [14]:
W2=np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
B2=np.array([0.1,0.2])
H2=np.dot(Z1,W2)+B2
Z2=sigmoid(H2)
print(Z2)

[0.62624937 0.7710107 ]


In [15]:
W3=np.array([[0.1,0.2],[0.2,0.3]])
B3=np.array([0.1,0.2])
H3=np.dot(Z2,W3)+B3
print(H3)

[0.31682708 0.55655308]


In [20]:
scores=np.array([20,10,1])
exp_s=np.exp(scores)

In [25]:
sum_exp_s=np.sum(exp_s)  # 지수함수의 합=485187224.5938669
sum_exp_s

485187224.5938669

In [27]:
y=exp_s / sum_exp_s
y

array([9.99954597e-01, 4.53978684e-05, 5.60254205e-09])