In [1]:
import nltk # <- natural language tool kit
nltk.__version__

'3.4.5'

In [2]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [3]:
nltk.download(treebank) # <- 따로 설치, 잘 안돼서 직접 다운

NameError: name 'treebank' is not defined

In [ ]:
#토큰화, 정제, 정규화
#토큰화: 어절, 단어, 문장, 문단

In [4]:
from nltk.tokenize import word_tokenize   # <- 단어별로 토큰화

In [5]:
from nltk.tokenize import sent_tokenize   # <- 문장별로 토큰화

In [6]:
print(word_tokenize("Mr. John's Don't be ")) #<-공백기준으로 다 나뉘고 ' 기준으로 나뉨

['Mr.', 'John', "'s", 'Do', "n't", 'be']


In [7]:
from nltk.tokenize import WordPunctTokenizer # Punctuation: 구두점
WordPunctTokenizer()

WordPunctTokenizer(pattern='\\w+|[^\\w\\s]+', gaps=False, discard_empty=True, flags=<RegexFlag.UNICODE|DOTALL|MULTILINE: 56>)

In [8]:
WordPunctTokenizer().tokenize("Mr. John's Don't be ")

['Mr', '.', 'John', "'", 's', 'Don', "'", 't', 'be']

In [9]:
print(word_tokenize("Mr. John's Don't be "))

['Mr.', 'John', "'s", 'Do', "n't", 'be']


In [10]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence

In [11]:
text_to_word_sequence("Mr. John's Don't be ")

['mr', "john's", "don't", 'be']

In [12]:
#자연어처리: 정규표현식을 잘 알아야함

In [13]:
from nltk.tokenize import TreebankWordTokenizer

In [14]:
sentence="Mr. John's Don't be "

In [15]:
twt=TreebankWordTokenizer()
print(twt.tokenize(sentence))

['Mr.', 'John', "'s", 'Do', "n't", 'be']


In [16]:
text="Python is an interpreted, high-level, general-purpose programming language. Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace. Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects."

In [17]:
text

"Python is an interpreted, high-level, general-purpose programming language. Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace. Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects."

In [18]:
from nltk.tokenize import sent_tokenize

In [19]:
print(sent_tokenize(text))
#조사: she her 같은 단어들
#한국어 토큰화 작업: 형태소(ex:가장 작은 말의단위) 고려해야함
#자립형태소/의존형태소
#ex: "길동이가 파이썬을 합니다"


['Python is an interpreted, high-level, general-purpose programming language.', "Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace.", 'Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.']


In [20]:
#품사 태깅(tagging): ex) fly 
#토큰화 과정에서 단어가 어떤 품사로 쓰였는지 구분하는 과정

In [21]:
text='Python is an interpreted, high-level, general-purpose programming language.'

In [22]:
print(word_tokenize(text))

['Python', 'is', 'an', 'interpreted', ',', 'high-level', ',', 'general-purpose', 'programming', 'language', '.']


In [23]:
from nltk.tag import pos_tag

In [24]:
pos_tag(word_tokenize(text)) #<- 품사별로 tagging이 됨

[('Python', 'NNP'),
 ('is', 'VBZ'),
 ('an', 'DT'),
 ('interpreted', 'JJ'),
 (',', ','),
 ('high-level', 'JJ'),
 (',', ','),
 ('general-purpose', 'JJ'),
 ('programming', 'NN'),
 ('language', 'NN'),
 ('.', '.')]

In [ ]:
NNP: 단수 고유명사
VB: 동사
VBP: 동사 현재형
TO: to 전치사
NN: 명사(단수형 혹은 집합형)
DT: 관형사

In [26]:
#(우리나라)형태소 분석기: Okt, Mecab, Kkma, ... 등
#우리나라말은 단어토큰화가 아님. 형태소 토큰화를 하는 것

In [27]:
from konlpy.tag import Okt

In [29]:
okt=Okt()
#morphs : 형태소 추출
print("- okt.morphs로 출력:\n",okt.morphs("오늘은 수요일, 내일은 목요일입니다."))
#pos : 품사 추출
print("- okt.pos로 출력:\n",okt.pos("오늘은 수요일, 내일은 목요일입니다."))
#nouns: 명사
print("- okt.nouns로 출력:\n",okt.nouns("오늘은 수요일, 내일은 목요일입니다."))
#konlpy.org 사이트 참조

- okt.morphs로 출력:
 ['오늘', '은', '수요일', ',', '내일', '은', '목요일', '입니다', '.']
- okt.pos로 출력:
 [('오늘', 'Noun'), ('은', 'Josa'), ('수요일', 'Noun'), (',', 'Punctuation'), ('내일', 'Noun'), ('은', 'Josa'), ('목요일', 'Noun'), ('입니다', 'Adjective'), ('.', 'Punctuation')]
- okt.nouns로 출력:
 ['오늘', '수요일', '내일', '목요일']


In [ ]:
from konlpy.tag import Kkma
kma=Kkma()
kma.morphs()  # <- 이런식으로 사용하면됨 사용법은 비슷함.

In [31]:
#데이터 정제(전처리): 불필요한 형태소 제거, 단어 통일(밥,식사,...)
#정규표현식을 이용 

In [ ]:
# LSA (Latent Semantic Analysis)
""" 문서: 1번  2번  3번              4번       5번           6번
ex)     떡만두 김밥 떡만두+김밥    |   피자  햄버거,쿠키,피자   햄버거   <- 문서
 ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
 떡만두   1    0     1
 김밥     0   1      1
 피자     0   0      0
 햄버거   0   0      0
 쿠키     0   0      0
 (^DTM)
"""
"""
유사도(4번문서,6번문서)?
=>cos유사도로 0이 나옴 (공통된단어가 없어서 내적하면 0이기때문)
토픽모델링의 한계가 생김
TF-IDF도 계산해봐야 0나옴
이유: 단어를 기반으로 유사도를 구하기 때문
"""

In [ ]:
"""
LSA 사용하면 토픽으로 유사도를 구하기 때문에
SVD(Singular Value Decomposition): 특이값 분해
A행렬 = mxn 행렬, 3개의 행렬의 곱형태로 분해
=>A=U*sigma*V^T  <-특이값 분해
U:토픽에 대한 단어 행렬
sigma: 토픽 강도
V^T: 토픽에 대한 문서행렬
"""

In [32]:
import numpy as np

In [34]:
# A 행렬은 DTM
A=np.array([[0,0,0,1,0,1,1,0,0],
            [0,0,0,1,1,0,1,0,0],
          [0,1,1,0,2,0,0,0,0],
          [0,0,0,0,0,0,0,1,1]])
A.shape

(4, 9)

In [35]:
U, s, VT =np.linalg.svd(A,full_matrices=True)  # <- full SVD , truncted(절단된) SVD도있음 

In [61]:
U=U.round(2) # <- 직교행렬
s=s.round(2)
VT=VT.round(2)
print(U,"\n", "-"*30,"\n", "\n",s,"\n","-"*30,"\n",VT)
print("s는 diagonal elements만 나와서 아래와 같이 숫자4개임 바꿔줘야함")

[[-0.24  0.75  0.    0.62]
 [-0.51  0.44  0.   -0.74]
 [-0.83 -0.49  0.    0.27]
 [ 0.    0.    1.    0.  ]] 
 ------------------------------ 
 
 [2.69 2.05 1.41 0.77] 
 ------------------------------ 
 [[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28  0.    0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58  0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.71  0.71]
 [-0.    0.35  0.35 -0.16 -0.25  0.8  -0.16  0.    0.  ]
 [-0.   -0.78 -0.01 -0.2   0.4   0.4  -0.2   0.    0.  ]
 [-0.58  0.28 -0.69 -0.1   0.21  0.21 -0.1   0.    0.  ]
 [-0.58 -0.14  0.35 -0.45 -0.1  -0.1   0.55  0.    0.  ]
 [ 0.41  0.1  -0.25 -0.39  0.07  0.07  0.32  0.5  -0.5 ]
 [ 0.41  0.1  -0.25 -0.39  0.07  0.07  0.32 -0.5   0.5 ]]
s는 diagonal elements만 나와서 아래와 같이 숫자4개임 바꿔줘야함


In [59]:
S=np.zeros((4,9))

In [62]:
S[:4,:4]=np.diag(s)

In [67]:
print("-특이값 행렬:",'\n',S)

-특이값 행렬: 
 [[2.69 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   2.05 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   1.41 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.77 0.   0.   0.   0.   0.  ]]


In [71]:
print(VT,"\n","VT shape:",VT.shape)

[[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28  0.    0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58  0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.71  0.71]
 [-0.    0.35  0.35 -0.16 -0.25  0.8  -0.16  0.    0.  ]
 [-0.   -0.78 -0.01 -0.2   0.4   0.4  -0.2   0.    0.  ]
 [-0.58  0.28 -0.69 -0.1   0.21  0.21 -0.1   0.    0.  ]
 [-0.58 -0.14  0.35 -0.45 -0.1  -0.1   0.55  0.    0.  ]
 [ 0.41  0.1  -0.25 -0.39  0.07  0.07  0.32  0.5  -0.5 ]
 [ 0.41  0.1  -0.25 -0.39  0.07  0.07  0.32 -0.5   0.5 ]] 
 VT shape: (9, 9)


In [83]:
dotUS=np.dot(U,S)
print(np.dot(dotUS,VT).round(2))
print(A)

[[ 0.   -0.   -0.    1.   -0.    1.01  1.    0.    0.  ]
 [ 0.    0.01  0.01  1.    1.01  0.    1.    0.    0.  ]
 [ 0.    1.01  1.01  0.01  2.   -0.    0.01  0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    1.    1.  ]]
[[0 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0]
 [0 0 0 0 0 0 0 1 1]]


In [84]:
np.allclose(A,np.dot(dotUS,VT).round(2))

False

In [85]:
#절단된(truncted) SVD
#토픽 2개
S=S[:2,:2]
print(S)

[[2.69 0.  ]
 [0.   2.05]]


In [ ]:
#특이값의 의미: 가장큰 값이 가장 큰 토픽을 의미함

In [89]:
U.shape #(4,4)
Utemp=U[:,:2] #<- (4,2) : 문서 4개, 토픽 2개
#U의 의미는 4개 문서 각각에 대한 잠재된 의미를 표현하고있는 
#수치 문서 벡터

In [90]:
VT.shape
VTtemp=VT[:2,:] #<- (2,9) : 토픽 2개, 단어 9개
# VT에서 각 열의 의미는 잠재 의미를 나타내기 위한 수치화된
# 단어 벡터
# 크기가 2인 행렬만: 가장 강한 두 가지만 뽑겠다

In [91]:
#Utemp*S*VTtemp !=A : A와는 다른 행렬로 나옴, 일부 손실했기 때문
#하지만 A의 상당 부분을 담고있음

In [95]:
Aprime=np.dot(np.dot(Utemp,S),VTtemp)
print(Aprime.round(2),'\n','-'*40,'\n',A)

[[ 0.   -0.17 -0.17  1.07  0.12  0.63  1.07  0.    0.  ]
 [ 0.    0.21  0.21  0.91  0.86  0.46  0.91  0.    0.  ]
 [ 0.    0.93  0.93  0.04  2.05 -0.17  0.04  0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.  ]] 
 ---------------------------------------- 
 [[0 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0]
 [0 0 0 0 0 0 0 1 1]]


In [98]:
print(np.dot(S,VTtemp),np.dot(S,VTtemp).shape)

[[ 0.     -0.8339 -0.8339 -0.7532 -2.152  -0.2421 -0.7532  0.      0.    ]
 [ 0.     -0.492  -0.492   1.189  -0.533   0.7585  1.189   0.      0.    ]] (2, 9)


In [100]:
print("첫번째 토픽:",np.dot(S,VTtemp).round(3)[0])
print("두번째 토픽:",np.dot(S,VTtemp).round(3)[1])

첫번째 토픽: [ 0.    -0.834 -0.834 -0.753 -2.152 -0.242 -0.753  0.     0.   ]
두번째 토픽: [ 0.    -0.492 -0.492  1.189 -0.533  0.758  1.189  0.     0.   ]
