In [2]:
from konlpy.corpus import kolaw
from konlpy.tag import Okt
from nltk.tokenize import sent_tokenize

In [3]:
c = kolaw.open("constitution.txt").read() #<- 헌법파일

In [4]:
sent_tokenize(c) #357

['대한민국헌법\n\n유구한 역사와 전통에 빛나는 우리 대한국민은 3·1운동으로 건립된 대한민국임시정부의 법통과 불의에 항거한 4·19민주이념을 계승하고, 조국의 민주개혁과 평화적 통일의 사명에 입각하여 정의·인도와 동포애로써 민족의 단결을 공고히 하고, 모든 사회적 폐습과 불의를 타파하며, 자율과 조화를 바탕으로 자유민주적 기본질서를 더욱 확고히 하여 정치·경제·사회·문화의 모든 영역에 있어서 각인의 기회를 균등히 하고, 능력을 최고도로 발휘하게 하며, 자유와 권리에 따르는 책임과 의무를 완수하게 하여, 안으로는 국민생활의 균등한 향상을 기하고 밖으로는 항구적인 세계평화와 인류공영에 이바지함으로써 우리들과 우리들의 자손의 안전과 자유와 행복을 영원히 확보할 것을 다짐하면서 1948년 7월 12일에 제정되고 8차에 걸쳐 개정된 헌법을 이제 국회의 의결을 거쳐 국민투표에 의하여 개정한다.',
 '제1장 총강\n  제1조 ① 대한민국은 민주공화국이다.',
 '②대한민국의 주권은 국민에게 있고, 모든 권력은 국민으로부터 나온다.',
 '제2조 ① 대한민국의 국민이 되는 요건은 법률로 정한다.',
 '②국가는 법률이 정하는 바에 의하여 재외국민을 보호할 의무를 진다.',
 '제3조 대한민국의 영토는 한반도와 그 부속도서로 한다.',
 '제4조 대한민국은 통일을 지향하며, 자유민주적 기본질서에 입각한 평화적 통일 정책을 수립하고 이를 추진한다.',
 '제5조 ① 대한민국은 국제평화의 유지에 노력하고 침략적 전쟁을 부인한다.',
 '②국군은 국가의 안전보장과 국토방위의 신성한 의무를 수행함을 사명으로 하며, 그 정치적 중립성은 준수된다.',
 '제6조 ① 헌법에 의하여 체결·공포된 조약과 일반적으로 승인된 국제법규는 국내법과 같은 효력을 가진다.',
 '②외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다.',
 '제7조 ① 공무원은 국민전체에 대한 봉사자이며, 국민에 대하여 책임을 진다.',
 '②공무원의 신분과 정치적 중립성은 법률이 정하는 바에 의하여 

In [7]:
doc0=[" ".join(["".join(w) for w,t in okt.pos(s) 
   if t not in ['Number','Foreign'] 
   and w not in ['제','조']]) for s in sent_tokenize(c) ]
    
    

In [6]:
okt = Okt()
okt.pos("오늘은 날씨가 따뜻합니다") #<- 품사에 대한 정보가 나옴

[('오늘', 'Noun'),
 ('은', 'Josa'),
 ('날씨', 'Noun'),
 ('가', 'Josa'),
 ('따뜻합니다', 'Adjective')]

In [8]:
doc0[2]

'대한민국 의 주권 은 국민 에게 있고 , 모든 권력 은 국민 으로부터 나온다 .'

In [9]:
from keras.preprocessing.text import Tokenizer

Using TensorFlow backend.


In [10]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(doc0) #<- 
doc = [tok for tok in tokenizer.texts_to_sequences(doc0) if len(tok)>1]

In [11]:
maxLen=max([len(x)-1 for x in doc])
print(maxLen)
vocabSize = len(tokenizer.word_index)+1
print(vocabSize)

187
1165


In [ ]:
--------------------------"05-14"-----------------------

In [12]:
from keras.models import Sequential
from keras.layers import Dense, Embedding, LSTM, Dropout
from keras.optimizers import *
from keras.utils import np_utils
from keras.preprocessing import sequence
from keras.preprocessing.text import Tokenizer

from nltk.tokenize import sent_tokenize
from konlpy.corpus import kolaw
from konlpy.tag import Okt

In [13]:
c = kolaw.open("constitution.txt").read() #<- 헌법파일

In [ ]:
type(c)

In [14]:
sent = [s for s in sent_tokenize(c)]

In [15]:
sent[3]

'제2조 ① 대한민국의 국민이 되는 요건은 법률로 정한다.'

In [16]:
okt=Okt()
temp = sent_tokenize(c)[0:5]
print(len(temp))
for i in range(10):
    for w,t in okt.pos(temp[i]): #<- konlpy.org: API => Okt
        print("w:",w)
        print("t:",t)

5
w: 대한민국
t: Noun
w: 헌법
t: Noun
w: 


t: Foreign
w: 유구
t: Noun
w: 한
t: Josa
w: 역사
t: Noun
w: 와
t: Josa
w: 전통
t: Noun
w: 에
t: Josa
w: 빛나는
t: Verb
w: 우리
t: Noun
w: 대
t: Modifier
w: 한
t: Modifier
w: 국민
t: Noun
w: 은
t: Josa
w: 3
t: Number
w: ·
t: Punctuation
w: 1
t: Number
w: 운동
t: Noun
w: 으로
t: Josa
w: 건립
t: Noun
w: 된
t: Verb
w: 대한민국
t: Noun
w: 임시정부
t: Noun
w: 의
t: Josa
w: 법
t: Noun
w: 통과
t: Noun
w: 불의
t: Noun
w: 에
t: Josa
w: 항거
t: Noun
w: 한
t: Josa
w: 4
t: Number
w: ·
t: Punctuation
w: 19
t: Number
w: 민주
t: Noun
w: 이념
t: Noun
w: 을
t: Josa
w: 계승
t: Noun
w: 하고
t: Josa
w: ,
t: Punctuation
w: 조국
t: Noun
w: 의
t: Josa
w: 민주
t: Noun
w: 개혁
t: Noun
w: 과
t: Josa
w: 평화
t: Noun
w: 적
t: Suffix
w: 통일
t: Noun
w: 의
t: Josa
w: 사명
t: Noun
w: 에
t: Josa
w: 입
t: Noun
w: 각하
t: Noun
w: 여
t: Josa
w: 정의
t: Noun
w: ·
t: Punctuation
w: 인도
t: Noun
w: 와
t: Josa
w: 동포
t: Noun
w: 애
t: Noun
w: 로써
t: Noun
w: 민족
t: Noun
w: 의
t: Josa
w: 단결
t: Noun
w: 을
t: Josa
w: 공고
t: Noun
w: 히
t: Adverb
w: 하고
t: Verb
w: ,
t: Punctuation

IndexError: list index out of range

In [ ]:
doc0=[" ".join(["".join(w) for w,t in okt.pos(s) 
   if t not in ['Number','Foreign'] 
   and w not in ['제','조']]) for s in sent_tokenize(c) ]

In [ ]:
type(doc0)

In [ ]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(doc0) #<- tokenizer

In [ ]:
tokenizer.index_word #<- doc0의 모든 text에 대해서 index가 붙음

In [17]:
len(tokenizer.index_word) #<- 1164: 중복 제외한 단어 개수
tokenizer.word_counts

OrderedDict([('대한민국', 11),
             ('헌법', 53),
             ('유구', 1),
             ('한', 101),
             ('역사', 1),
             ('와', 41),
             ('전통', 1),
             ('에', 281),
             ('빛나는', 1),
             ('우리', 3),
             ('대', 1),
             ('국민', 61),
             ('은', 179),
             ('·', 145),
             ('운동', 2),
             ('으로', 43),
             ('건립', 1),
             ('된', 30),
             ('임시정부', 1),
             ('의', 372),
             ('법', 3),
             ('통과', 1),
             ('불의', 2),
             ('항거', 1),
             ('민주', 6),
             ('이념', 1),
             ('을', 208),
             ('계승', 2),
             ('하고', 19),
             ('조국', 3),
             ('개혁', 1),
             ('과', 82),
             ('평화', 6),
             ('적', 35),
             ('통일', 6),
             ('사명', 2),
             ('입', 1),
             ('각하', 1),
             ('여', 10),
             ('정의', 1),
             ('인도', 1),
   

In [18]:
tokenizer.texts_to_sequences(doc0) # 문서의 단어 index

[[102,
  28,
  602,
  11,
  603,
  33,
  604,
  2,
  605,
  323,
  606,
  11,
  22,
  4,
  7,
  427,
  32,
  607,
  40,
  102,
  608,
  1,
  324,
  609,
  428,
  2,
  610,
  11,
  7,
  177,
  611,
  3,
  429,
  59,
  325,
  1,
  177,
  612,
  16,
  178,
  37,
  179,
  1,
  430,
  2,
  613,
  614,
  110,
  615,
  7,
  616,
  33,
  617,
  618,
  215,
  326,
  1,
  619,
  3,
  327,
  620,
  59,
  34,
  136,
  37,
  621,
  16,
  428,
  8,
  622,
  38,
  431,
  16,
  432,
  8,
  623,
  32,
  433,
  37,
  137,
  259,
  138,
  8,
  624,
  625,
  23,
  122,
  7,
  63,
  7,
  136,
  7,
  260,
  1,
  34,
  261,
  2,
  123,
  626,
  1,
  328,
  8,
  627,
  59,
  329,
  3,
  434,
  628,
  629,
  262,
  38,
  55,
  33,
  49,
  2,
  630,
  216,
  16,
  64,
  8,
  631,
  262,
  23,
  50,
  435,
  22,
  139,
  1,
  436,
  217,
  3,
  632,
  263,
  633,
  435,
  634,
  37,
  47,
  635,
  178,
  33,
  636,
  637,
  2,
  638,
  218,
  264,
  323,
  437,
  16,
  323,
  437,
  1,
  639,
  1,
  640,
  16,
 

In [19]:
import numpy as np

In [20]:
np.shape(tokenizer.texts_to_sequences(doc0))

(357,)

In [21]:
doc = [a for a in tokenizer.texts_to_sequences(doc0) if len(a) >1]

In [22]:
#확인용 cell
for  a in tokenizer.texts_to_sequences(doc0):
    print(a)
    print("="*40,"<-문단구분선")

[102, 28, 602, 11, 603, 33, 604, 2, 605, 323, 606, 11, 22, 4, 7, 427, 32, 607, 40, 102, 608, 1, 324, 609, 428, 2, 610, 11, 7, 177, 611, 3, 429, 59, 325, 1, 177, 612, 16, 178, 37, 179, 1, 430, 2, 613, 614, 110, 615, 7, 616, 33, 617, 618, 215, 326, 1, 619, 3, 327, 620, 59, 34, 136, 37, 621, 16, 428, 8, 622, 38, 431, 16, 432, 8, 623, 32, 433, 37, 137, 259, 138, 8, 624, 625, 23, 122, 7, 63, 7, 136, 7, 260, 1, 34, 261, 2, 123, 626, 1, 328, 8, 627, 59, 329, 3, 434, 628, 629, 262, 38, 55, 33, 49, 2, 630, 216, 16, 64, 8, 631, 262, 23, 50, 435, 22, 139, 1, 436, 217, 3, 632, 263, 633, 435, 634, 37, 47, 635, 178, 33, 636, 637, 2, 638, 218, 264, 323, 437, 16, 323, 437, 1, 639, 1, 640, 16, 55, 33, 438, 3, 641, 642, 12, 154, 3, 643, 644, 140, 330, 265, 2, 645, 180, 40, 28, 3, 646, 19, 1, 70, 3, 647, 155, 2, 20, 180, 6]
======================================== <-문단구분선
[45, 439, 648, 102, 4, 649, 650]
======================================== <-문단구분선
[102, 1, 440, 4, 22, 141, 266, 34, 651, 4, 22, 331, 

In [23]:
#확인용 cell
for  a in tokenizer.texts_to_sequences(doc0):
    if len(a) <=1:
        print(len(a),"3개의 문장은 길이가 0 즉 결측치")

0 3개의 문장은 길이가 0 즉 결측치
0 3개의 문장은 길이가 0 즉 결측치
0 3개의 문장은 길이가 0 즉 결측치


In [24]:
maxLen = max([len(x) for x in doc])
tokenizer.word_counts #<- 어떤 단어가 몇번 언급되었는지

OrderedDict([('대한민국', 11),
             ('헌법', 53),
             ('유구', 1),
             ('한', 101),
             ('역사', 1),
             ('와', 41),
             ('전통', 1),
             ('에', 281),
             ('빛나는', 1),
             ('우리', 3),
             ('대', 1),
             ('국민', 61),
             ('은', 179),
             ('·', 145),
             ('운동', 2),
             ('으로', 43),
             ('건립', 1),
             ('된', 30),
             ('임시정부', 1),
             ('의', 372),
             ('법', 3),
             ('통과', 1),
             ('불의', 2),
             ('항거', 1),
             ('민주', 6),
             ('이념', 1),
             ('을', 208),
             ('계승', 2),
             ('하고', 19),
             ('조국', 3),
             ('개혁', 1),
             ('과', 82),
             ('평화', 6),
             ('적', 35),
             ('통일', 6),
             ('사명', 2),
             ('입', 1),
             ('각하', 1),
             ('여', 10),
             ('정의', 1),
             ('인도', 1),
   

In [25]:
vocabSize = len(tokenizer.word_index)+1 #1164 +1
print("maxLen:",maxLen,"\n","vocabSize:",vocabSize)

maxLen: 188 
 vocabSize: 1165


In [26]:
"""
RNN 돌릴려면 문장의 길이를 통일 시켜주어야함
"""

'\nRNN 돌릴려면 문장의 길이를 통일 시켜주어야함\n'

In [27]:
len(doc[1])

7

In [28]:
doc[1]

[45, 439, 648, 102, 4, 649, 650]

In [29]:
#코드 전체의 예로 [45, 439, 648, 102, 4, 649, 650]일 경우
def genData(doc, maxLen, vocabSize):
    for sent in doc: #ex: sent의 길이가 7
        inputs=[]
        targets=[]
        for i in range(1, len(sent)): # range는 1~6까지 반복
            inputs.append(sent[0:i]) #<- [[45], [45, 439]...]
            targets.append(sent[i])  #<- [[439],[638]...]
        y = np_utils.to_categorical(targets,vocabSize) #[439]=>[0,..,0,1,...0]
        inputSeq = sequence.pad_sequences(inputs, maxlen=maxLen)
        yield (inputSeq,y)
        #print("inputs:",inputs,"\n","="*50)
        #print("targets:",targets)   
#    return 

In [30]:
# yield와 return의 차이
# 함수 구현시 return하면 그냥 끝나는데
# yield를 하면 객체를 줌

In [31]:
for i, (x,y) in enumerate(genData(doc,maxLen, vocabSize)):
    print(i)
    print("x's shape:",x.shape,"\n",x)
    print("y's shape:",y.shape,"\n",y)

0
x's shape: (187, 188) 
 [[  0   0   0 ...   0   0 102]
 [  0   0   0 ...   0 102  28]
 [  0   0   0 ... 102  28 602]
 ...
 [  0   0   0 ... 647 155   2]
 [  0   0 102 ... 155   2  20]
 [  0 102  28 ...   2  20 180]]
y's shape: (187, 1165) 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
1
x's shape: (6, 188) 
 [[  0   0   0 ...   0   0  45]
 [  0   0   0 ...   0  45 439]
 [  0   0   0 ...  45 439 648]
 [  0   0   0 ... 439 648 102]
 [  0   0   0 ... 648 102   4]
 [  0   0   0 ... 102   4 649]]
y's shape: (6, 1165) 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
2
x's shape: (12, 188) 
 [[  0   0   0 ...   0   0 102]
 [  0   0   0 ...   0 102   1]
 [  0   0   0 ... 102   1 440]
 ...
 [  0   0   0 ...  34 651   4]
 [  0   0   0 ... 651   4  22]
 [  0   0   0 ...   4  22 331]]

In [32]:
xdata=[]
ydata=[]
for x,y in genData(doc, maxLen, vocabSize):
    xdata.append(x)
    ydata.append(y)
xdata=np.concatenate(xdata)
ydata=np.concatenate(ydata)

In [33]:
xdata #<- array들을 합치는 작업을 하는게 좋음
xdata #<- 합쳐졌나 확인용
print(len(xdata))

6917


In [34]:
#연습용
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8],[9,10]])
print(np.concatenate((a,b),axis=0),
      np.concatenate((a,b.T),axis=1),
      np.concatenate((a,b),axis=None))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] [[ 1  2  5  7  9]
 [ 3  4  6  8 10]] [ 1  2  3  4  5  6  7  8  9 10]


In [68]:
#모델만들기
model=Sequential()
model.add(Embedding(vocabSize,100,input_length=maxLen)) #<- 1165,100
#Embed:끼워넣기 퍼가기
model.add(LSTM(100, return_sequences=False))
model.add(Dropout(0.5))
model.add(Dense(vocabSize,activation='softmax'))


In [36]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 188, 100)          116500    
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               80400     
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1165)              117665    
Total params: 314,565
Trainable params: 314,565
Non-trainable params: 0
_________________________________________________________________


In [37]:
model.compile(loss='categorical_crossentropy',
             optimizer='rmsprop', #<-RMSprop() 함수로 써도됨
             metrics=['accuracy'])

In [38]:
hist=model.fit(xdata,ydata,epochs=500,batch_size=800)


Epoch 1/500
6917/6917 [==============================] - 13s 2ms/step - loss: 6.6924 - accuracy: 0.0357
Epoch 2/500
6917/6917 [==============================] - 13s 2ms/step - loss: 5.8682 - accuracy: 0.0470
Epoch 3/500
5600/6917 [=======================>......] - ETA: 2s - loss: 5.7627 - accuracy: 0.0473

KeyboardInterrupt: 

In [40]:
import matplotlib.pyplot as plt

In [39]:
plt.plot(hist.history['accuracy'])
plt.show()
model.save("textGen.h5")

NameError: name 'plt' is not defined

In [84]:
path='C:/Users/김경한/jupyter notebook data/'
file='ChatData.csv'

In [85]:
path+file

'C:/Users/김경한/jupyter notebook data/ChatData.csv'

In [87]:
chatbotData['Q']

0                         12시 땡!
1                    1지망 학교 떨어졌어
2                   3박4일 놀러가고 싶다
3                3박4일 정도 놀러가고 싶다
4                        PPL 심하네
                  ...           
11818             훔쳐보는 것도 눈치 보임.
11819             훔쳐보는 것도 눈치 보임.
11820                흑기사 해주는 짝남.
11821    힘든 연애 좋은 연애라는게 무슨 차이일까?
11822                 힘들어서 결혼할까봐
Name: Q, Length: 11823, dtype: object

In [86]:
chatbotData=pd.read_csv(path+file, 
                        encoding="utf-8")
question, answer=list(chatbotData['Q']),list(chatbotData['A'])

In [88]:
question=question[:100]
answer=answer[:100]

In [ ]:
for i in range(5):
    print(question[i])
    print(answer[i])

In [46]:
import re
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os
from konlpy.tag import Okt
from keras import models,layers,optimizers,metrics,preprocessing

In [83]:
#태그 단어
PAD='<PADDING>' #패딩
STA='<START>' #시작
END='<END>' #끝
OOV='<OOV>' #out of vocabulary

PAD_index=0
STA_index=1
END_index=2
OOV_index=3

ENCODER_INPUT = 0
DECODER_INPUT = 1
DECODER_TARGET = 2

#한 문장에서 단어 시퀀스의 최대 개수
maxSequences = 30
#임베딩 벡터 차원
embeddingDim = 100
#LSTM 출력 차원
lstmHiddenDim =128
#정규표현식 필터
RE_FILTER = re.compile("[.,!?₩';:~()]")


In [81]:
#형태소 분석기
def posTag(sentences):
    tagger=Okt()
    sentencePos=[]
    for sentence in sentences:
        #특수문자 제거
        sentence = re.sub(RE_FILTER,"",sentence) #<- sentence에 있는 RE_FILTER에 해당되면 제거해라
        sentence = " ".join(tagger.morphs(sentence))#<-형태소로 나뉘는 애를 sentence에
        sentencePos.append(sentence)
        
    return sentencePos

In [89]:
question = posTag(question)
answer = posTag(answer)

In [90]:
#질문 + 대답 문장을 하나로 합치기
sentences=[]
sentences.extend(question)
sentences.extend(answer) #<- extend: 길게 하나로 쭉 이어붙혀짐
len(sentences)


200

In [91]:
words=[]
#단어 배열 생성
for sentence in sentences:
    for word in sentence.split():
        words.append(word)
len(words) #<- 966

966

In [92]:
"실습"
#1.words에서 길이가 0인 단어를 삭제
#2.중복단어 삭제

'실습'

In [93]:
words=[word for word in words if len(word)>0]

In [94]:
len(words) #<- 길이가 0인 단어가 없음

966

In [95]:
words = list(set(words)) #<-중복단어제거
len(words) #<-단어가 엄청 줄어들음

450

In [96]:
words[:0] = [PAD, STA, END, OOV] #<- 맨 앞에 집어 넣기
words[2]

'<END>'

In [97]:
words[:20]

['<PADDING>',
 '<START>',
 '<END>',
 '<OOV>',
 '기관',
 '중요한',
 '됐으면',
 'SNS',
 '꼈어',
 '안',
 '빼고',
 '하느라',
 '먹어야지',
 '걔',
 '먹고',
 '싶다',
 '입어',
 '너무',
 '잠깐',
 '말까']

In [98]:
#단어에 대한 인덱스를 부여 -> 딕셔너리
wordToIndex = {word:index for index, word in enumerate(words)}
indexToWord = {index:word for index, word in enumerate(words)}

In [99]:
wordToIndex

{'<PADDING>': 0,
 '<START>': 1,
 '<END>': 2,
 '<OOV>': 3,
 '기관': 4,
 '중요한': 5,
 '됐으면': 6,
 'SNS': 7,
 '꼈어': 8,
 '안': 9,
 '빼고': 10,
 '하느라': 11,
 '먹어야지': 12,
 '걔': 13,
 '먹고': 14,
 '싶다': 15,
 '입어': 16,
 '너무': 17,
 '잠깐': 18,
 '말까': 19,
 '하루': 20,
 '지망': 21,
 '그럴': 22,
 '인데': 23,
 '건데': 24,
 '업무': 25,
 '기운': 26,
 '두': 27,
 '중요해요': 28,
 '싶네요': 29,
 '3초': 30,
 '심하네': 31,
 '나를': 32,
 '키울': 33,
 '짧죠': 34,
 '봐서': 35,
 'ㅠㅠ': 36,
 '떨리니까': 37,
 '즐기세요': 38,
 '가지': 39,
 '감미로운': 40,
 '감정': 41,
 '가까워질': 42,
 '첫인상': 43,
 '이라니': 44,
 '알아차려도': 45,
 '개인': 46,
 '출발': 47,
 '옆': 48,
 '해봐요': 49,
 '가난한': 50,
 '있을': 51,
 '시켜': 52,
 '매일': 53,
 '왜': 54,
 '12시': 55,
 '생각': 56,
 '주는': 57,
 '정말': 58,
 '정': 59,
 '살펴': 60,
 '여행': 61,
 '같아': 62,
 '가네요': 63,
 '가려고': 64,
 '후회': 65,
 '리지': 66,
 '난다': 67,
 '했잖아': 68,
 '갑자기': 69,
 '입어볼까': 70,
 '자의': 71,
 '살까': 72,
 '맛있게': 73,
 '붙잡고': 74,
 '무시': 75,
 '와': 76,
 '부족했나': 77,
 '가세': 78,
 '이야': 79,
 '끌': 80,
 '어디': 81,
 '카드': 82,
 '나온거': 83,
 '나': 84,
 '서로': 85,
 '정도': 86,
 'SD': 

In [ ]:
#전처리
#문장 -> 인덱스로 변환

In [ ]:
""" shift + tab : 내어쓰기,
    tab: 들여쓰기
    """

In [80]:
def convertTextToIndex(sentences, voc, mytype):
    sentencesIndex=[]
    for sentence in sentences:
        sentenceIndex=[]
        if mytype==DECODER_INPUT:
            
            sentenceIndex.extend([voc[STA]]) #<- 1추가
            
        for word in sentence.split():
            
            if voc.get(word) is not None:
                sentenceIndex.extend([voc[word]]) #<- 단어에 해당하는 index가 추가
                
            else: #<-단어가 사전에 없는 경우
                sentenceIndex.extend([voc[OOV]]) #<- OOV를 추가
                
        if mytype==DECODER_TARGET:
            #디코더 출력은 맨 마지막에 end가 추가
            if maxSequences<=len(sentenceIndex):
                sentenceIndex = sentenceIndex[:maxSequences-1]+[voc[END]]
            else:
                sentenceIndex+=[voc[END]]
        else:
            if len( sentenceIndex)> maxSequences:
                sentenceIndex=sentenceIndex[:maxSequences]
        #0으로채우기(paddig)
        sentenceIndex+=[wordToIndex[PAD]]*(maxSequences-len(sentenceIndex))    
        sentencesIndex.append(sentenceIndex)
    return np.asarray(sentencesIndex) #<-list가 array로 바뀌어서 return

In [100]:
#test
sentenceIndex+=[wordToIndex[PAD]]*(maxSequences-len(sentenceIndex))

NameError: name 'sentenceIndex' is not defined

In [103]:
ENCODER_INPUT

0

In [101]:
#인코더 입력, 디코더 입력, 디코더 출력 -> 인덱스 변환
xEncoder = convertTextToIndex(question, wordToIndex, ENCODER_INPUT)
xDecoder = convertTextToIndex(answer, wordToIndex, DECODER_INPUT)
yDecoder = convertTextToIndex(answer, wordToIndex, DECODER_TARGET)

In [107]:
yDecoder[0]

array([ 20, 293, 220,  63,   2,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0])

In [ ]:
인코더 입력 : 12시 땡
디코더 입력 : START 하루 가  또 가네요
디코더 출력 : 하루    가 또 가네요 END

In [114]:
np.zeros((2,3,4))
print(len(yDecoder),maxSequences,len(words))
print("100:답변 개수",",30:최대 단어 길이(개수)",",454:전체 단어 집합 개수")
print("100개의 답변에 단어의 갯수가 30개씩 있는데 각각을 원핫인코딩하면 길이가 454가 됨")

100 30 454
100:답변 개수 ,30:최대 단어 길이(개수) ,454:전체 단어 집합 개수
100개의 답변에 단어의 갯수가 30개씩 있는데 각각을 원핫인코딩하면 길이가 454가 됨


In [115]:
oneHotData = np.zeros((len(yDecoder),maxSequences,len(words)))

In [121]:
oneHotData.shape #<- decoder의 출력으로
yDecoder.shape
for i, seq in enumerate(yDecoder): #<-(100,30)
    for j, index in enumerate(seq): #<- 답변에 해당하는 단어의 index
        oneHotData[i,j,index]=1 #<- onehotencoding 됨
yDecoder = oneHotData
yDecoder[0]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [ ]:
*keras로 모델 만드는 2가지 방법
1.seqential()
2.함수형 api사용

In [131]:
#모델 생성
#인코더 정의
#입력 문장의 인덱스 sequence를 입력
encoderInputs = layers.Input(shape=(None,))    #<-입력에 대한 정의를 해줌
#Embedding 계층
encoderOutputs = layers.Embedding(len(words), embeddingDim)(encoderInputs)

#<-입력변수설명: 1번째 출력(hidden)shape
encoderOutputs, stateH, stateC = layers.LSTM(lstmHiddenDim,return_state=True,
                                           dropout=0.2,
                                            recurrent_dropout=0.5)(encoderOutputs)
#return_state=True => 상태값이 리턴
#LSTM은 상태가 2개 존재함(셀스테이트,히든스테이트)

encoderStates = [stateH, stateC]

#디코더 정의
#출력 문장의 인덱스 sequence를 입력
decoderInputs = layers.Input(shape=(None,))    #<-출력에 대한 정의를 해줌
#Embedding 계층
decoderEmbedding = layers.Embedding(len(words), embeddingDim)
decoderOutputs = decoderEmbedding(decoderInputs)

#입력변수설명: 1번째 출력(hidden)shape
decoderLSTM= layers.LSTM(lstmHiddenDim,return_state=True,
                                           return_sequences=True, dropout=0.2,
                                            recurrent_dropout=0.5)
decoderOutputs, _,_ = decoderLSTM(decoderOutputs,
                                  initial_state = encoderStates) #<-초기상태:encoderStates
decoderDense = layers.Dense(len(words), activation='softmax')
decoderOutputs = decoderDense(decoderOutputs)


In [128]:
model = models.Model( [encoderInputs,decoderInputs],
                     decoderOutputs)

In [129]:
model.compile(optimizer='rmsprop',
             loss='categorical_crossentropy',
             metrics=['accuracy'])
#여기까지가 훈련과 관련된 모델 정의

In [133]:
#예측 모델에 대한 encoder 정의
encoderModel = models.Model(encoderInputs,
                            encoderStates)

#예측 모델에 대한 decoder 정의
#바로 앞에 있는 decoder의 출력(state)을 입력받아서 예측해야 함
decoderStateInputH = layers.Input(shape=(lstmHiddenDim,))
decoderStateInputC = layers.Input(shape=(lstmHiddenDim,))
decoderStatesInputs = [decoderStateInputH, decoderStateInputC]

#Embedding layer
decoderOutputs = decoderEmbedding(decoderInputs)

#LSTM layer
decoderOutputs, stateH, stateC = decoderLSTM(decoderOutputs,
           initial_state = decoderStatesInputs)
decoderStates = [stateH, stateC]

#Dense layer를 통해 원핫 형식으로 예측단어 인
decoderOutputs = decoderDense(decoderOutputs)

#예측 모델 decoder 설정
models.Model([decoderInputs+decoderStatesInputs,
             [decoderOutputs]+decoderStates])







In [136]:
def converIndexToText(indexs,voc):
    #구현
    sentence = ''
    for i in indexs:
        if i==END_INDEX:
            break;
        if voc.get(i) is not None:
            sentence+=voc[i]
        else:
            sentence.extend([voc[OOV_INDEX]])
        sentence+=" "
    return sentence

In [135]:
for epoch in range(20):
    print("total epoch:",epoch+1)
    history = model.fit([xEncoder,xDecoder],yDecoder,
    epochs=100,batch_size=64,verbose=0)
    print("accuracy:",history.history['accuracy'])
    print("loss:",history.history['loss'])

total epoch: 1
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/100
100/100 [==============================] - 1s 6ms/step - loss: 6.0688 - accuracy: 0.2827
Epoch 2/100
100/100 [==============================] - 0s 1ms/step - loss: 5.2472 - accuracy: 0.7863
Epoch 3/100
100/100 [==============================] - 0s 2ms/step - loss: 2.5249 - accuracy: 0.7863
Epoch 4/100
100/100 [==============================] - 0s 2ms/step - loss: 1.6493 - accuracy: 0.7863
Epoch 5/100
100/100 [==============================] - 0s 2ms/step - loss: 1.4963 - accuracy: 0.7863
Epoch 6/100
100/100 [==============================] - 0s 2ms/step - loss: 1.4357 - accuracy: 0.7863
Epoch 7/100
100/100 [==============================] - 0s 2ms/step - loss: 1.3835 - accuracy: 0.7863
Epoch 8/100
100/100 [==============================] - 0s 2ms/step - loss: 1.3598 - accuracy: 0.7863
Epoch 9/100
100/100 [==============================] - 0s 2ms/step - loss: 1.3254 -

In [137]:
#문장예측
#3박 4일 놀러가고 싶다->
inputEncoder=xEncoder[2].reshape(1,xEncoder)
inputDecoder=xDecoder[2].reshape(1,xDecoder)

results=model.predict([inputEncoder,input])
# 결과값에 대하여 가장 큰 값의 위치를 구함
index = np.argmax(results[0],1)
# index -> 문장
sentence = converIndexToText(index,indexToWord)
print(sentence)
print()

TypeError: only integer scalar arrays can be converted to a scalar index

In [44]:
from keras.models import load_model
model=load_model(path+file)

In [43]:
path='C:/Users/김경한/jupyter notebook data/'
file="tentGen.hdf5"

In [45]:
wordList="대한민국 의 국민 이 되는 요건 은 법률 로 정한 다 ."
wordList

'대한민국 의 국민 이 되는 요건 은 법률 로 정한 다 .'

In [47]:
reverseWordMap = dict(map(reversed,tokenizer.word_index.items()))
len(reverseWordMap)

1164

In [65]:
x = sequence.pad_sequences([[tokenizer.word_index[w] for w in wordList[:2]]],
                       maxlen=maxLen)
x #<-wordList에 대한민국,의 를 가져와서 padding한거

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0

In [66]:
print(maxLen)

188


In [63]:
type(tokenizer.word_index.items())

dict_items

In [74]:
p = model.predict(x)[0]
p.argsort()

array([509, 284, 679, ..., 954, 403, 254], dtype=int64)

In [73]:
# argsort
te = np.array([2.5,1.5,0,1])
te.argsort() #<- index로 sort해서 나옴

array([2, 3, 1, 0], dtype=int64)

In [75]:
idx = np.flip(np.argsort(p),0)
p[idx]

array([0.00087186, 0.00087178, 0.00087175, ..., 0.00084644, 0.00084618,
       0.00084598], dtype=float32)

In [76]:
for i in idx[:10]:
    print(reverseWordMap[i])

감사원
대통령령
합니다
직전
동포
근로
상실한
과학기술
무상


KeyError: 0

In [78]:
def predictWord(i,n):
    x = sequence.pad_sequences([[tokenizer.word_index[w] for w in wordList[:i]]],
                            maxlen=maxLen)
    p = model.predict(x)[0]    
    idx = np.flip(np.argsort(p),0)
    for j in idx[:n]:#<- n개만큼 추출
        print(" ".join(wordList[:i]), reverseWordMap[j])

In [79]:
predictWord(1,3) #<- 1:대한민국, 3: 3개 추천
wordList

대 대통령령
대 직전
대 근로


'대한민국 의 국민 이 되는 요건 은 법률 로 정한 다 .'

In [143]:
#문장 입력
def makePredictInput(sentence):
    sentences = []
    sentences.append(sentence)
    sentences = posTag(sentences)
    inputSeq = converIndexToText(sentences,
                                 wordToIndex,
                                 ENCODER_INPUT)
    return inputSeq

In [138]:
#예측 답변 생성
def generateText(inputSeq):
    #입력을 인코더에 넣고 마지막 상태값을 구하기
    states = encoderModel.predict(inputSeq)
    
    #목표 시퀀스 초기화
    targetSeq = np.zeros((1,1))
    #<START> 시그널을 추가
    targetSeq[0,0] = STA_INDEX #<- <STA>의 tag index
    #index 초기화
    indexs=[]
    
    #decoder 반복
    while 1: #<-계속반복
        decoderOutputs, stateH, stateC = decoderModel.predict( [targetSeq]+states)
        #결과를 원하인코딩형식으로변환
        index= np.argmax(decoderOutputs[0,0,:])
        indexs.append(index)
        #종료 체크
        if index == END_INDEX or len(indexs)>=maxSequences:
            break #<- 최대길이를 넘어가면 while을 빠져나가야함
    
        targetSeq = np.zeros((1,1))
        targetSeq[0,0] = index            #<-STA_INDEX
    
        #decoder의 이전 상태를 다음 decoder예측
        states = [stateH,stateC]
    #index를 문장으로 변환해주면됨
    sentence = converIndexToText(indexs,indexToWord)
    
    return sentence
        

In [144]:
#입력문장 -> index로 먼저 선행되어여함

inputSeq=makePredictInput("3박4일 놀러가고 싶다")
#[[320, 157, .... ,19,0,0,0,...,0]]

TypeError: converIndexToText() takes 2 positional arguments but 3 were given

In [145]:
sentence = generateText(inputSeq)
sentence #<- "여행은 언제나 좋죠"

NameError: name 'inputSeq' is not defined