In [1]:
from konlpy.corpus import kolaw
from konlpy.tag import Okt
from nltk.tokenize import sent_tokenize

In [2]:
c = kolaw.open("constitution.txt").read() #<- 헌법파일

In [4]:
sent_tokenize(c) #357

['대한민국헌법\n\n유구한 역사와 전통에 빛나는 우리 대한국민은 3·1운동으로 건립된 대한민국임시정부의 법통과 불의에 항거한 4·19민주이념을 계승하고, 조국의 민주개혁과 평화적 통일의 사명에 입각하여 정의·인도와 동포애로써 민족의 단결을 공고히 하고, 모든 사회적 폐습과 불의를 타파하며, 자율과 조화를 바탕으로 자유민주적 기본질서를 더욱 확고히 하여 정치·경제·사회·문화의 모든 영역에 있어서 각인의 기회를 균등히 하고, 능력을 최고도로 발휘하게 하며, 자유와 권리에 따르는 책임과 의무를 완수하게 하여, 안으로는 국민생활의 균등한 향상을 기하고 밖으로는 항구적인 세계평화와 인류공영에 이바지함으로써 우리들과 우리들의 자손의 안전과 자유와 행복을 영원히 확보할 것을 다짐하면서 1948년 7월 12일에 제정되고 8차에 걸쳐 개정된 헌법을 이제 국회의 의결을 거쳐 국민투표에 의하여 개정한다.',
 '제1장 총강\n  제1조 ① 대한민국은 민주공화국이다.',
 '②대한민국의 주권은 국민에게 있고, 모든 권력은 국민으로부터 나온다.',
 '제2조 ① 대한민국의 국민이 되는 요건은 법률로 정한다.',
 '②국가는 법률이 정하는 바에 의하여 재외국민을 보호할 의무를 진다.',
 '제3조 대한민국의 영토는 한반도와 그 부속도서로 한다.',
 '제4조 대한민국은 통일을 지향하며, 자유민주적 기본질서에 입각한 평화적 통일 정책을 수립하고 이를 추진한다.',
 '제5조 ① 대한민국은 국제평화의 유지에 노력하고 침략적 전쟁을 부인한다.',
 '②국군은 국가의 안전보장과 국토방위의 신성한 의무를 수행함을 사명으로 하며, 그 정치적 중립성은 준수된다.',
 '제6조 ① 헌법에 의하여 체결·공포된 조약과 일반적으로 승인된 국제법규는 국내법과 같은 효력을 가진다.',
 '②외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다.',
 '제7조 ① 공무원은 국민전체에 대한 봉사자이며, 국민에 대하여 책임을 진다.',
 '②공무원의 신분과 정치적 중립성은 법률이 정하는 바에 의하여 

In [9]:
doc0=[" ".join(["".join(w) for w,t in okt.pos(s) 
   if t not in ['Number','Foreign'] 
   and w not in ['제','조']]) for s in sent_tokenize(c) ]
    
    

In [6]:
okt = Okt()
okt.pos("오늘은 날씨가 따뜻합니다") #<- 품사에 대한 정보가 나옴

[('오늘', 'Noun'),
 ('은', 'Josa'),
 ('날씨', 'Noun'),
 ('가', 'Josa'),
 ('따뜻합니다', 'Adjective')]

In [12]:
doc0[2]

'대한민국 의 주권 은 국민 에게 있고 , 모든 권력 은 국민 으로부터 나온다 .'

In [18]:
from keras.preprocessing.text import Tokenizer

In [19]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(doc0) #<- 
doc = [tok for tok in tokenizer.texts_to_sequences(doc0) if len(tok)>1]

In [20]:
maxLen=max([len(x)-1 for x in doc])
print(maxLen)
vocabSize = len(tokenizer.word_index)+1
print(vocabSize)

187
1165


In [ ]:
--------------------------"05-14"-----------------------

In [1]:
from keras.models import Sequential
from keras.layers import Dense, Embedding, LSTM, Dropout
from keras.optimizers import *
from keras.utils import np_utils
from keras.preprocessing import sequence
from keras.preprocessing.text import Tokenizer

from nltk.tokenize import sent_tokenize
from konlpy.corpus import kolaw
from konlpy.tag import Okt

Using TensorFlow backend.


In [2]:
c = kolaw.open("constitution.txt").read() #<- 헌법파일

In [3]:
type(c)

str

In [4]:
sent = [s for s in sent_tokenize(c)]

In [5]:
sent[3]

'제2조 ① 대한민국의 국민이 되는 요건은 법률로 정한다.'

In [9]:
okt=Okt()
temp = sent_tokenize(c)[0:5]
print(len(temp))
for i in range(10):
    for w,t in okt.pos(temp[i]): #<- konlpy.org: API => Okt
        print("w:",w)
        print("t:",t)

5
w: 대한민국
t: Noun
w: 헌법
t: Noun
w: 


t: Foreign
w: 유구
t: Noun
w: 한
t: Josa
w: 역사
t: Noun
w: 와
t: Josa
w: 전통
t: Noun
w: 에
t: Josa
w: 빛나는
t: Verb
w: 우리
t: Noun
w: 대
t: Modifier
w: 한
t: Modifier
w: 국민
t: Noun
w: 은
t: Josa
w: 3
t: Number
w: ·
t: Punctuation
w: 1
t: Number
w: 운동
t: Noun
w: 으로
t: Josa
w: 건립
t: Noun
w: 된
t: Verb
w: 대한민국
t: Noun
w: 임시정부
t: Noun
w: 의
t: Josa
w: 법
t: Noun
w: 통과
t: Noun
w: 불의
t: Noun
w: 에
t: Josa
w: 항거
t: Noun
w: 한
t: Josa
w: 4
t: Number
w: ·
t: Punctuation
w: 19
t: Number
w: 민주
t: Noun
w: 이념
t: Noun
w: 을
t: Josa
w: 계승
t: Noun
w: 하고
t: Josa
w: ,
t: Punctuation
w: 조국
t: Noun
w: 의
t: Josa
w: 민주
t: Noun
w: 개혁
t: Noun
w: 과
t: Josa
w: 평화
t: Noun
w: 적
t: Suffix
w: 통일
t: Noun
w: 의
t: Josa
w: 사명
t: Noun
w: 에
t: Josa
w: 입
t: Noun
w: 각하
t: Noun
w: 여
t: Josa
w: 정의
t: Noun
w: ·
t: Punctuation
w: 인도
t: Noun
w: 와
t: Josa
w: 동포
t: Noun
w: 애
t: Noun
w: 로써
t: Noun
w: 민족
t: Noun
w: 의
t: Josa
w: 단결
t: Noun
w: 을
t: Josa
w: 공고
t: Noun
w: 히
t: Adverb
w: 하고
t: Verb
w: ,
t: Punctuation

IndexError: list index out of range

In [10]:
doc0=[" ".join(["".join(w) for w,t in okt.pos(s) 
   if t not in ['Number','Foreign'] 
   and w not in ['제','조']]) for s in sent_tokenize(c) ]

In [15]:
type(doc0)

list

In [17]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(doc0) #<- tokenizer

In [18]:
tokenizer.index_word #<- doc0의 모든 text에 대해서 index가 붙음

{1: '의',
 2: '에',
 3: '을',
 4: '은',
 5: '이',
 6: '한다',
 7: '·',
 8: '를',
 9: '법률',
 10: '는',
 11: '한',
 12: '할',
 13: '정',
 14: '수',
 15: '대통령',
 16: '과',
 17: '국가',
 18: '또는',
 19: '국회',
 20: '의하여',
 21: '하는',
 22: '국민',
 23: '하여',
 24: '로',
 25: '관',
 26: '있다',
 27: '때',
 28: '헌법',
 29: '그',
 30: '에는',
 31: '가',
 32: '으로',
 33: '와',
 34: '모든',
 35: '바',
 36: '위',
 37: '적',
 38: '하며',
 39: '하여야',
 40: '된',
 41: '아니',
 42: '기타',
 43: '가진다',
 44: '및',
 45: '장',
 46: '사항',
 47: '인',
 48: '에서',
 49: '권리',
 50: '안',
 51: '된다',
 52: '필요한',
 53: '없다',
 54: '의원',
 55: '자유',
 56: '정부',
 57: '선거',
 58: '임명',
 59: '하고',
 60: '되지',
 61: '직무',
 62: '국무총리',
 63: '경제',
 64: '의무',
 65: '조직',
 66: '자',
 67: '하',
 68: '국회의원',
 69: '임기',
 70: '의결',
 71: '공무원',
 72: '경우',
 73: '이상',
 74: '국무위원',
 75: '대법원',
 76: '하기',
 77: '범위',
 78: '이를',
 79: '다',
 80: '될',
 81: '받지',
 82: '법관',
 83: '보호',
 84: '정책',
 85: '정당',
 86: '헌법재판소',
 87: '재적',
 88: '회의',
 89: '항의',
 90: '관리',
 91: '진다',
 92: '노력',
 93: '보장',
 

In [24]:
len(tokenizer.index_word) #<- 1164: 중복 제외한 단어 개수
tokenizer.word_counts

OrderedDict([('대한민국', 11),
             ('헌법', 53),
             ('유구', 1),
             ('한', 101),
             ('역사', 1),
             ('와', 41),
             ('전통', 1),
             ('에', 281),
             ('빛나는', 1),
             ('우리', 3),
             ('대', 1),
             ('국민', 61),
             ('은', 179),
             ('·', 145),
             ('운동', 2),
             ('으로', 43),
             ('건립', 1),
             ('된', 30),
             ('임시정부', 1),
             ('의', 372),
             ('법', 3),
             ('통과', 1),
             ('불의', 2),
             ('항거', 1),
             ('민주', 6),
             ('이념', 1),
             ('을', 208),
             ('계승', 2),
             ('하고', 19),
             ('조국', 3),
             ('개혁', 1),
             ('과', 82),
             ('평화', 6),
             ('적', 35),
             ('통일', 6),
             ('사명', 2),
             ('입', 1),
             ('각하', 1),
             ('여', 10),
             ('정의', 1),
             ('인도', 1),
   

In [25]:
tokenizer.texts_to_sequences(doc0) # 문서의 단어 index

[[102,
  28,
  602,
  11,
  603,
  33,
  604,
  2,
  605,
  323,
  606,
  11,
  22,
  4,
  7,
  427,
  32,
  607,
  40,
  102,
  608,
  1,
  324,
  609,
  428,
  2,
  610,
  11,
  7,
  177,
  611,
  3,
  429,
  59,
  325,
  1,
  177,
  612,
  16,
  178,
  37,
  179,
  1,
  430,
  2,
  613,
  614,
  110,
  615,
  7,
  616,
  33,
  617,
  618,
  215,
  326,
  1,
  619,
  3,
  327,
  620,
  59,
  34,
  136,
  37,
  621,
  16,
  428,
  8,
  622,
  38,
  431,
  16,
  432,
  8,
  623,
  32,
  433,
  37,
  137,
  259,
  138,
  8,
  624,
  625,
  23,
  122,
  7,
  63,
  7,
  136,
  7,
  260,
  1,
  34,
  261,
  2,
  123,
  626,
  1,
  328,
  8,
  627,
  59,
  329,
  3,
  434,
  628,
  629,
  262,
  38,
  55,
  33,
  49,
  2,
  630,
  216,
  16,
  64,
  8,
  631,
  262,
  23,
  50,
  435,
  22,
  139,
  1,
  436,
  217,
  3,
  632,
  263,
  633,
  435,
  634,
  37,
  47,
  635,
  178,
  33,
  636,
  637,
  2,
  638,
  218,
  264,
  323,
  437,
  16,
  323,
  437,
  1,
  639,
  1,
  640,
  16,
 

In [26]:
import numpy as np

In [27]:
np.shape(tokenizer.texts_to_sequences(doc0))

(357,)

In [28]:
doc = [a for a in tokenizer.texts_to_sequences(doc0) if len(a) >1]

In [31]:
#확인용 cell
for  a in tokenizer.texts_to_sequences(doc0):
    print(a)
    print("="*40,"<-문단구분선")

[102, 28, 602, 11, 603, 33, 604, 2, 605, 323, 606, 11, 22, 4, 7, 427, 32, 607, 40, 102, 608, 1, 324, 609, 428, 2, 610, 11, 7, 177, 611, 3, 429, 59, 325, 1, 177, 612, 16, 178, 37, 179, 1, 430, 2, 613, 614, 110, 615, 7, 616, 33, 617, 618, 215, 326, 1, 619, 3, 327, 620, 59, 34, 136, 37, 621, 16, 428, 8, 622, 38, 431, 16, 432, 8, 623, 32, 433, 37, 137, 259, 138, 8, 624, 625, 23, 122, 7, 63, 7, 136, 7, 260, 1, 34, 261, 2, 123, 626, 1, 328, 8, 627, 59, 329, 3, 434, 628, 629, 262, 38, 55, 33, 49, 2, 630, 216, 16, 64, 8, 631, 262, 23, 50, 435, 22, 139, 1, 436, 217, 3, 632, 263, 633, 435, 634, 37, 47, 635, 178, 33, 636, 637, 2, 638, 218, 264, 323, 437, 16, 323, 437, 1, 639, 1, 640, 16, 55, 33, 438, 3, 641, 642, 12, 154, 3, 643, 644, 140, 330, 265, 2, 645, 180, 40, 28, 3, 646, 19, 1, 70, 3, 647, 155, 2, 20, 180, 6]
======================================== <-문단구분선
[45, 439, 648, 102, 4, 649, 650]
======================================== <-문단구분선
[102, 1, 440, 4, 22, 141, 266, 34, 651, 4, 22, 331, 

In [33]:
#확인용 cell
for  a in tokenizer.texts_to_sequences(doc0):
    if len(a) <=1:
        print(len(a),"3개의 문장은 길이가 0 즉 결측치")

0 3개의 문장은 길이가 0 즉 결측치
0 3개의 문장은 길이가 0 즉 결측치
0 3개의 문장은 길이가 0 즉 결측치


In [34]:
maxLen = max([len(x) for x in doc])
tokenizer.word_counts #<- 어떤 단어가 몇번 언급되었는지

OrderedDict([('대한민국', 11),
             ('헌법', 53),
             ('유구', 1),
             ('한', 101),
             ('역사', 1),
             ('와', 41),
             ('전통', 1),
             ('에', 281),
             ('빛나는', 1),
             ('우리', 3),
             ('대', 1),
             ('국민', 61),
             ('은', 179),
             ('·', 145),
             ('운동', 2),
             ('으로', 43),
             ('건립', 1),
             ('된', 30),
             ('임시정부', 1),
             ('의', 372),
             ('법', 3),
             ('통과', 1),
             ('불의', 2),
             ('항거', 1),
             ('민주', 6),
             ('이념', 1),
             ('을', 208),
             ('계승', 2),
             ('하고', 19),
             ('조국', 3),
             ('개혁', 1),
             ('과', 82),
             ('평화', 6),
             ('적', 35),
             ('통일', 6),
             ('사명', 2),
             ('입', 1),
             ('각하', 1),
             ('여', 10),
             ('정의', 1),
             ('인도', 1),
   

In [37]:
vocabSize = len(tokenizer.word_index)+1 #1164 +1
print("maxLen:",maxLen,"\n","vocabSize:",vocabSize)

maxLen: 188 
 vocabSize: 1165


In [ ]:
"""
RNN 돌릴려면 문장의 길이를 통일 시켜주어야함
"""

In [38]:
len(doc[1])

7

In [40]:
doc[1]

[45, 439, 648, 102, 4, 649, 650]

In [44]:
#코드 전체의 예로 [45, 439, 648, 102, 4, 649, 650]일 경우
def genData(doc, maxLen, vocabSize):
    for sent in doc: #ex: sent의 길이가 7
        inputs=[]
        targets=[]
        for i in range(1, len(sent)): # range는 1~6까지 반복
            inputs.append(sent[0:i]) #<- [[45], [45, 439]...]
            targets.append(sent[i])  #<- [[439],[638]...]
        y = np_utils.to_categorical(targets,vocabSize) #[439]=>[0,..,0,1,...0]
        inputSeq = sequence.pad_sequences(inputs, maxlen=maxLen)
        yield (inputSeq,y)
        #print("inputs:",inputs,"\n","="*50)
        #print("targets:",targets)   
#    return 

In [ ]:
# yield와 return의 차이
# 함수 구현시 return하면 그냥 끝나는데
# yield를 하면 객체를 줌

In [47]:
for i, (x,y) in enumerate(genData(doc,maxLen, vocabSize)):
    print(i)
    print("x's shape:",x.shape,"\n",x)
    print("y's shape:",y.shape,"\n",y)

0
x's shape: (187, 188) 
 [[  0   0   0 ...   0   0 102]
 [  0   0   0 ...   0 102  28]
 [  0   0   0 ... 102  28 602]
 ...
 [  0   0   0 ... 647 155   2]
 [  0   0 102 ... 155   2  20]
 [  0 102  28 ...   2  20 180]]
y's shape: (187, 1165) 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
1
x's shape: (6, 188) 
 [[  0   0   0 ...   0   0  45]
 [  0   0   0 ...   0  45 439]
 [  0   0   0 ...  45 439 648]
 [  0   0   0 ... 439 648 102]
 [  0   0   0 ... 648 102   4]
 [  0   0   0 ... 102   4 649]]
y's shape: (6, 1165) 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
2
x's shape: (12, 188) 
 [[  0   0   0 ...   0   0 102]
 [  0   0   0 ...   0 102   1]
 [  0   0   0 ... 102   1 440]
 ...
 [  0   0   0 ...  34 651   4]
 [  0   0   0 ... 651   4  22]
 [  0   0   0 ...   4  22 331]]

In [57]:
xdata=[]
ydata=[]
for x,y in genData(doc, maxLen, vocabSize):
    xdata.append(x)
    ydata.append(y)
xdata=np.concatenate(xdata)
ydata=np.concatenate(ydata)

In [59]:
xdata #<- array들을 합치는 작업을 하는게 좋음
xdata #<- 합쳐졌나 확인용
print(len(xdata))

6917


In [56]:
#연습용
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8],[9,10]])
print(np.concatenate((a,b),axis=0),
      np.concatenate((a,b.T),axis=1),
      np.concatenate((a,b),axis=None))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] [[ 1  2  5  7  9]
 [ 3  4  6  8 10]] [ 1  2  3  4  5  6  7  8  9 10]


In [60]:
#모델만들기
model=Sequential()
model.add(Embedding(vocabSize,100,input_length=maxLen)) #<- 1165,100
#Embed:끼워넣기 퍼가기
model.add(LSTM(100, return_sequences=False))
model.add(Dropout(0.5))
model.add(Dense(vocabSize,activation='softmax'))


Instructions for updating:
If using Keras pass *_constraint arguments to layers.


<bound method Network.summary of <keras.engine.sequential.Sequential object at 0x000002046B491488>>

In [61]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 188, 100)          116500    
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               80400     
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1165)              117665    
Total params: 314,565
Trainable params: 314,565
Non-trainable params: 0
_________________________________________________________________


In [63]:
model.compile(loss='categorical_crossentropy',
             optimizer='rmsprop', #<-RMSprop() 함수로 써도됨
             metrics=['accuracy'])

In [64]:
hist=model.fit(xdata,ydata,epochs=500,batch_size=800)


Epoch 1/500
6917/6917 [==============================] - 13s 2ms/step - loss: 6.6476 - accuracy: 0.0224
Epoch 2/500
6917/6917 [==============================] - 13s 2ms/step - loss: 5.8589 - accuracy: 0.0364
Epoch 3/500
6917/6917 [==============================] - 13s 2ms/step - loss: 5.7431 - accuracy: 0.0470
Epoch 4/500
6917/6917 [==============================] - 13s 2ms/step - loss: 5.7324 - accuracy: 0.0499
Epoch 5/500
6917/6917 [==============================] - 14s 2ms/step - loss: 5.7188 - accuracy: 0.0442
Epoch 6/500
6917/6917 [==============================] - 13s 2ms/step - loss: 5.6967 - accuracy: 0.0477
Epoch 7/500
6917/6917 [==============================] - 13s 2ms/step - loss: 5.6767 - accuracy: 0.0492
Epoch 8/500
6917/6917 [==============================] - 13s 2ms/step - loss: 5.6421 - accuracy: 0.0515
Epoch 9/500
6917/6917 [==============================] - 15s 2ms/step - loss: 5.6051 - accuracy: 0.0513
Epoch 10/500
6917/6917 [==============================] - 16s 2

KeyboardInterrupt: 

In [65]:
plt.plot(hist.history['accuracy'])
plt.show()
model.save("textGen.h5")

NameError: name 'plt' is not defined

In [71]:
path='C:/Users/김경한/jupyter notebook data/'
file='ChatData.csv'

In [73]:
path+file

'C:/Users/김경한/jupyter notebook data/ChatData.csv'

In [74]:
chatbotData['Q']

0                         12시 땡!
1                    1지망 학교 떨어졌어
2                   3박4일 놀러가고 싶다
3                3박4일 정도 놀러가고 싶다
4                        PPL 심하네
                  ...           
11818             훔쳐보는 것도 눈치 보임.
11819             훔쳐보는 것도 눈치 보임.
11820                흑기사 해주는 짝남.
11821    힘든 연애 좋은 연애라는게 무슨 차이일까?
11822                 힘들어서 결혼할까봐
Name: Q, Length: 11823, dtype: object

In [76]:
chatbotData=pd.read_csv(path+file, 
                        encoding="utf-8")
question, answer=list(chatbotData['Q']),list(chatbotData['A'])

In [77]:
question=question[:100]
answer=answer[:100]

In [78]:
for i in range(5):
    print(question[i])
    print(answer[i])

12시 땡!
하루가 또 가네요.
1지망 학교 떨어졌어
위로해 드립니다.
3박4일 놀러가고 싶다
여행은 언제나 좋죠.
3박4일 정도 놀러가고 싶다
여행은 언제나 좋죠.
PPL 심하네
눈살이 찌푸려지죠.


In [70]:
import re
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os
from konlpy.tag import Okt
from keras import models,layers,optimizers,metrics,preprocessing

In [69]:
#태그 단어
PAD='<PADDING>' #패딩
STA='<START>' #시작
END='<END>' #끝
OOV='<OOV>' #out of vocabulary

PAD_index=0
STA_index=1
END_index=2
OOV_index=3

ENCODER_INPUT = 0
DECODER_INPUT = 1
DECODER_TARGET = 2

#한 문장에서 단어 시퀀스의 최대 개수
maxSequences = 30
#임베딩 벡터 차원
embeddingDim = 100
#LSTM 출력 차원
lstmHiddenDim =128
#정규표현식 필터
RE_FILTER = re.compile("[.,!?₩';:~()]")


In [80]:
#형태소 분석기
def posTag(sentences):
    tagger=Okt()
    sentencePos=[]
    for sentence in sentences:
        #특수문자 제거
        sentence = re.sub(RE_FILTER,"",sentence) #<- sentence에 있는 RE_FILTER에 해당되면 제거해라
        sentence = " ".join(tagger.morphs(sentence))#<-형태소로 나뉘는 애를 sentence에
        sentencePos.append(sentence)
        
    return sentencePos

In [81]:
question = posTag(question)
answer = posTag(answer)

['12시 땡',
 '1 지망 학교 떨어졌어',
 '3 박 4일 놀러 가고 싶다',
 '3 박 4일 정도 놀러 가고 싶다',
 'PPL 심하네',
 'SD 카드 망가졌어',
 'SD 카드 안 돼',
 'SNS 맞팔 왜 안 하지 ㅠㅠ',
 'SNS 시간 낭비 인 거 아는데 매일 하는 중',
 'SNS 시간 낭비 인데 자꾸 보게 됨',
 'SNS 보면 나 만 빼고 다 행복 해보여',
 '가끔 궁금해',
 '가끔 뭐 하는지 궁금해',
 '가끔 은 혼자 인게 좋다',
 '가난한 자의 설움',
 '가만 있어도 땀 난다',
 '가상 화폐 쫄딱 망함',
 '가스 불 켜고 나갔어',
 '가스 불 켜놓고 나온거 같아',
 '가스 비 너무 많이 나왔다',
 '가스 비 비싼데 감기 걸리겠어',
 '가스 비 장난 아님',
 '가장 확실한 건 뭘 까',
 '가족 여행 가기 로 했어',
 '가족 여행 고고',
 '가족 여행 어디 로 가지',
 '가족 있어',
 '가족 관계 알려 줘',
 '가족 끼리 여행 간다',
 '가족 들 보고 싶어',
 '가족 들 이랑 서먹해',
 '가족 들 이랑 서먹해졌어',
 '가족 들 이랑 어디 가지',
 '가족 들 이랑 여행 갈거야',
 '가족 여행 가야 지',
 '가족 이 누구 야',
 '가족 이랑 여행 가려고',
 '가족 한테 스트레스 풀었어',
 '가출 할까',
 '가출 해도 갈 데 가 없어',
 '간만 에 떨리니까 좋더라',
 '간만 에 쇼핑 중',
 '간만 에 휴식 중',
 '간식 뭐 먹을까',
 '간식 추천',
 '간장 치킨 시켜야지',
 '간접흡연 싫어',
 '갈까 말까 고민 돼',
 '갈까 말까',
 '감 말랭이 먹고 싶다',
 '감 말랭이 먹어야지',
 '감기 같 애',
 '감기 걸린 것 같아',
 '감기 기운 이 있어',
 '감기 들 거 같 애',
 '감기 가 오려나',
 '감기 약 이 없어',
 '감기 인거 같 애',
 '감미로운 목소리 좋아',
 '감정 이 쓰레기통 처럼 엉망 진창 이야',
 '감정 컨트롤 을 못 하겠어',
 '감정 컨

In [88]:
#질문 + 대답 문장을 하나로 합치기
sentences=[]
sentences.extend(question)
sentences.extend(answer) #<- extend: 길게 하나로 쭉 이어붙혀짐
len(sentences)


200

In [90]:
words=[]
#단어 배열 생성
for sentence in sentences:
    for word in sentence.split():
        words.append(word)
len(words) #<- 966

966

In [ ]:
"실습"
#1.words에서 길이가 0인 단어를 삭제
#2.중복단어 삭제

In [91]:
words=[word for word in words if len(word)>0]

In [92]:
len(words) #<- 길이가 0인 단어가 없음

966

In [93]:
words = list(set(words)) #<-중복단어제거
len(words) #<-단어가 엄청 줄어들음

450

In [98]:
words[:0] = [PAD, STA, END, OOV] #<- 맨 앞에 집어 넣기
words[2]

'<END>'

In [99]:
words[:20]

['<PADDING>',
 '<START>',
 '<END>',
 '<OOV>',
 '업무',
 '나오세요',
 '곧',
 '놓고',
 '알아차리지',
 '벗어나는',
 '누굴',
 '눈살',
 '가장',
 '알',
 '강아지',
 '낭비',
 '시켜야지',
 '또',
 '수',
 '새']

In [100]:
#단어에 대한 인덱스를 부여 -> 딕셔너리
wordToIndex = {word:index for index, word in enumerate(words)}
indexToWord = {index:word for index, word in enumerate(words)}

In [101]:
wordToIndex

{'<PADDING>': 0,
 '<START>': 1,
 '<END>': 2,
 '<OOV>': 3,
 '업무': 4,
 '나오세요': 5,
 '곧': 6,
 '놓고': 7,
 '알아차리지': 8,
 '벗어나는': 9,
 '누굴': 10,
 '눈살': 11,
 '가장': 12,
 '알': 13,
 '강아지': 14,
 '낭비': 15,
 '시켜야지': 16,
 '또': 17,
 '수': 18,
 '새': 19,
 '기름': 20,
 '갈거야': 21,
 '책임질': 22,
 '인데': 23,
 '자도': 24,
 '들더라': 25,
 '물어봐서': 26,
 '좋죠': 27,
 '어제': 28,
 '마세요': 29,
 '온': 30,
 '이랑': 31,
 '기회': 32,
 '좋아': 33,
 '처럼': 34,
 '키울': 35,
 '진리': 36,
 '집': 37,
 '하지': 38,
 '마음': 39,
 '하는데': 40,
 '했길': 41,
 '같은': 42,
 '목소리': 43,
 '되나': 44,
 '정말': 45,
 '죠': 46,
 '왔나': 47,
 '은': 48,
 '일해': 49,
 '모두': 50,
 '물어': 51,
 '관계': 52,
 '두': 53,
 '하자고': 54,
 '위로': 55,
 '하느라': 56,
 '여행': 57,
 '카드': 58,
 '맞팔': 59,
 '낮잠': 60,
 '좋겠네요': 61,
 '매일': 62,
 '새로': 63,
 '화폐': 64,
 '그런거니': 65,
 '가서': 66,
 '당신': 67,
 '참': 68,
 '되겠네요': 69,
 '12시': 70,
 '같이': 71,
 '하고': 72,
 '좋은': 73,
 '있어도': 74,
 '을': 75,
 '봅니다': 76,
 '운': 77,
 '소중해요': 78,
 '적': 79,
 '부족했나': 80,
 '예요': 81,
 '저': 82,
 '상황': 83,
 '남겨야': 84,
 '출발': 85,
 '이라니': 86,
 '키워': 87,
 '불'

In [102]:
#전처리
#문장 -> 인덱스로 변환

In [103]:
""" shift + tab : 내어쓰기,
    tab: 들여쓰기
    """

' shift + tab : 내어쓰기,\n    tab: 들여쓰기\n    '

In [108]:
def convertTextToIndex(sentences, voc, mytype):
    sentencesIndex=[]
    for sentence in sentences:
        sentenceIndex=[]
        if mytype==DECODER_INPUT:
            sentenceIndex.extend([voc[STA]]) #<- 1추가
        for word in sentence.split():
            if voc.get(word) is not None:
                sentenceIndex.extend([voc[word]]) #<- 단어에 해당하는 index가 추가
            else: #<-단어가 사전에 없는 경우
                sentenceIndex.extend([voc[OOV]]) #<- OOV를 추가
                
        if mytype==DECODER_TARGET:
            #디코더 출력은 맨 마지막에 end가 추가
            if maxSequences<=len(sentenceIndex):
                sentenceIndex = sentenceIndex[:maxSequences-1]+[voc[END]]
            else:
                sentenceIndex+=[voc[END]]
        else:
            if len( sentenceIndex)> maxSequences:
                sentenceIndex=sentenceIndex[:maxSequences]
        #0으로채우기(paddig)
        sentenceIndex+=[wordToIndex[PAD]]*(maxSequences-len(sentenceIndex))    
        sentencesIndex.append(sentenceIndex)
    return np.asarray(sentencesIndex) #<-list가 array로 바뀌어서 return

In [105]:
#test
sentenceIndex+=[wordToIndex[PAD]]*(maxSequences-len(sentenceIndex))

[0, 0, 0, 0, 0]

In [109]:
#인코더 입력, 디코더 입력, 디코더 출력 -> 인덱스 변환
xEncoder = convertTextToIndex(question, wordToIndex, ENCODER_INPUT)
xDecoder = convertTextToIndex(answer, wordToIndex, DECODER_INPUT)
yDecoder = convertTextToIndex(answer, wordToIndex, DECODER_TARGET)

In [ ]:
인코더 입력 : 12시 땡
디코더 입력 : START 하루 가  또 가네요
디코더 출력 : 하루    가 또 가네요 END